# for ordered data

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df=pd.read_csv(r'E:\code\AI study\ML\code\3) Feature engineering\customer.csv')
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

## ordinal encoding on review and education
## lable encoding on purchased

In [33]:
df=df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [34]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(df.iloc[:,:2],
                                           df.iloc[:,-1],
                                           test_size=0.2
                                           )

xtrain

     review education
48     Good        UG
34  Average    School
11     Good        UG
44  Average        UG
39     Poor        PG
24  Average        PG
32  Average        UG
31     Poor    School
8   Average        UG
47     Good        PG
23     Good    School
9      Good        UG
38     Good    School
1      Poor        UG
0   Average    School
19     Poor        PG
46     Poor        PG
28     Poor    School
35     Poor    School
2      Good        PG
26     Poor        PG
18     Good    School
17     Poor        UG
5   Average    School
14     Poor        PG
21  Average        PG
10     Good        UG
29  Average        UG
36     Good        UG
20  Average    School
15     Poor        UG
6      Good    School
37  Average        PG
27     Poor        PG
22     Poor        PG
45     Poor        PG
30  Average        UG
3      Good        PG
12     Poor    School
4   Average        UG

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(xtrain)

xtrainscaled=oe.transform(xtrain)
xtestscaled=oe.transform(xtest)

In [36]:
xtrainscaled = pd.DataFrame(xtrainscaled, columns=xtrain.columns)
xtestscaled = pd.DataFrame(xtestscaled, columns=xtest.columns)

xtrainscaled

    review  education
0      2.0        1.0
1      1.0        0.0
2      2.0        1.0
3      1.0        1.0
4      0.0        2.0
5      1.0        2.0
6      1.0        1.0
7      0.0        0.0
8      1.0        1.0
9      2.0        2.0
10     2.0        0.0
11     2.0        1.0
12     2.0        0.0
13     0.0        1.0
14     1.0        0.0
15     0.0        2.0
16     0.0        2.0
17     0.0        0.0
18     0.0        0.0
19     2.0        2.0
20     0.0        2.0
21     2.0        0.0
22     0.0        1.0
23     1.0        0.0
24     0.0        2.0
25     1.0        2.0
26     2.0        1.0
27     1.0        1.0
28     2.0        1.0
29     1.0        0.0
30     0.0        1.0
31     2.0        0.0
32     1.0        2.0
33     0.0        2.0
34     0.0        2.0
35     0.0        2.0
36     1.0        1.0
37     2.0        2.0
38     0.0        0.0
39     1.0        1.0