In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r'E:\code\AI study\ML\code\3) Feature engineering\cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

# Checking the no of catagories

In [3]:
print(df['brand'].nunique())
df['brand'].value_counts()

32

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [4]:
print(df['fuel'].nunique())
df['fuel'].value_counts()

4

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [5]:
print(df['owner'].nunique())
df['owner'].value_counts()

5

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(df.iloc[:,:4],
                                           df.iloc[:,-1],
                                           test_size=0.2
                                           )

xtrain

         brand  km_driven    fuel         owner
7115      Tata     120000  Diesel  Second Owner
1798    Maruti      43000  Petrol   First Owner
431    Hyundai     135000  Diesel  Second Owner
4484   Renault      96000  Diesel   First Owner
580     Maruti      50000  Petrol  Second Owner
...        ...        ...     ...           ...
4957    Maruti      31000  Diesel  Second Owner
1636  Mahindra     110000  Diesel   First Owner
3450    Toyota      73000  Diesel   First Owner
4168      Ford      20000  Diesel   First Owner
5565    Maruti     100000  Petrol   Third Owner

[6502 rows x 4 columns]

In [7]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(drop='first',sparse_output=False)

xtrainscaled=ohe.fit_transform(xtrain[['fuel','owner']])
xtestscaled=ohe.transform(xtest[['fuel','owner']])

xtrainscaled

array([[1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 1.]], shape=(6502, 7))

In [8]:
np.hstack((xtrain[['brand','km_driven']].values,xtrainscaled)).shape

(6502, 9)

# Encoding Brands

In [9]:
cnt=df['brand'].value_counts()
cnt

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [10]:
threshold=100
repl=cnt[cnt<=threshold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Kia',
       'Ambassador', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='str', name='brand')

In [11]:
pd.get_dummies(df['brand'].replace(repl,'Rare'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Rare,Renault,Skoda,Tata,Toyota,Volkswagen
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,False,True,False,False
8127,False,False,False,False,False,False,False,False,False,False,True,False,False